default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: umbrellio_forum_development

test:
  <<: *default
  database: umbrellio_forum_test
#
production:
  <<: *default
  database: umbrellio_forum_production
  username: umbrellio_forum
  password: <%= ENV['UMBRELLIO_FORUM_DATABASE_PASSWORD'] %>
